name: "Gonzalez-Kozlova"
description: "This is the official web page for the Edgar Gonzalez-Kozlova"

url: "https://eegk.github.io/"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
