name: "Gonzalez-Kozlova Lab"
description: "This is the official web page for the Edgar Gonzalez-Kozlova Lab at UVa."

url: "https://eegk.github.io/"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
